version: "2"

run:
  timeout: 10m
  tests: false

linters:
  enable:
    - ineffassign
    - unused
    - errcheck
    - govet
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
