version: "2"

run:
  timeout: 10m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

    - path: examples/
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0