version: "2"

run:
  timeout: 10m
  tests: false

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - errcheck

settings:
  govet:
    disable:
      - buildtag
  staticcheck:
    checks:
      - all
      - -QF*

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
