version: "2"

run:
  timeout: 10m
  tests: false

linters:
  enable:
    - ineffassign
    - unused
    - errcheck
    - govet
    - staticcheck
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Print
        - fmt.Printf
        - fmt.Println
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST*"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: pkg/sql/parser/token_conversion\.go
      linters:
        - staticcheck
      text: "SA1019"
