version: "2"

run:
  timeout: 10m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

exclusions:
  rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: examples/
      linters:
        - errcheck
