package models

// TokenType represents the type of a SQL token
type TokenType int

const (
	TokenTypeUnknown TokenType = iota
	TokenTypeEOF
	TokenTypeIdentifier
	TokenTypeString
	TokenTypeNumber
	TokenTypeEquals
	TokenTypeLessEquals
	TokenTypeGreaterEquals
	TokenTypeNotEquals
	TokenTypeKeyword
	TokenTypeSelect
	TokenTypeFrom
	TokenTypeWhere
	TokenTypeAnd
	TokenTypeOr
	TokenTypeAs
	TokenTypeJoin
	TokenTypeInner
	TokenTypeLeft
	TokenTypeRight
	TokenTypeOuter
	TokenTypeLeftJoin
	TokenTypeRightJoin
	TokenTypeInnerJoin
	TokenTypeOuterJoin
	TokenTypeFullJoin
	TokenTypeCrossJoin
	TokenTypeNaturalJoin
	TokenTypeOn
	TokenTypeUsing
	TokenTypeGroup
	TokenTypeBy
	TokenTypeGroupBy
	TokenTypeHaving
	TokenTypeOrder
	TokenTypeOrderBy
	TokenTypeAsc
	TokenTypeDesc
	TokenTypeLimit
	TokenTypeOffset
	TokenTypeInsert
	TokenTypeInto
	TokenTypeValues
	TokenTypeUpdate
	TokenTypeSet
	TokenTypeDelete
	TokenTypeAll
	TokenTypeFetch
	TokenTypeNext
	TokenTypeRows
	TokenTypeOnly
	TokenTypeWith
	TokenTypeTies
	TokenTypeNulls
	TokenTypeFirst
	TokenTypeLast
	TokenTypeOperator
	TokenTypePlus
	TokenTypeMinus
	TokenTypeAsterisk
	TokenTypeSlash
	TokenTypePercent
	TokenTypeConcat
	TokenTypeCast
	TokenTypeArrow
	TokenTypeDoubleArrow
	TokenTypeDoubleColon
	TokenTypeComma
	TokenTypeSemicolon
	TokenTypeDot
	TokenTypeCaret
	TokenTypePipe
	TokenTypeAmpersand
	TokenTypeTilde
	TokenTypeExclamation
	TokenTypeQuestion
	TokenTypeColon
	TokenTypeLeftParen
	TokenTypeRightParen
	TokenTypeLeftBracket
	TokenTypeRightBracket
	TokenTypeLeftBrace
	TokenTypeRightBrace
	TokenTypeCount
	TokenTypeSum
	TokenTypeAvg
	TokenTypeMin
	TokenTypeCancelled
	TokenTypeMax
	TokenTypeDistinct
	TokenTypeNull
	TokenTypeTrue
	TokenTypeFalse
	TokenTypeIn
	TokenTypeBetween
	TokenTypeLike
	TokenTypeIs
	TokenTypeNot
	TokenTypeExists
	TokenTypeCase
	TokenTypeWhen
	TokenTypeThen
	TokenTypeElse
	TokenTypeEnd
	TokenTypeCreate
	TokenTypeTable
	TokenTypeIndex
	TokenTypeView
	TokenTypeDatabase
	TokenTypeAlter
	TokenTypeDrop
	TokenTypeConstraint
	TokenTypePrimary
	TokenTypeForeign
	TokenTypeKey
	TokenTypeUnique
	TokenTypeDefault
	TokenTypeCheck
	TokenTypeAutoIncrement
	TokenTypeReferences
	TokenTypeCascade
	TokenTypeRestrict
	TokenTypeNoAction
	TokenTypeSetNull
	TokenTypeLessThan
	TokenTypeLessThanEqual
	TokenTypeGreaterThan
	TokenTypeGreaterThanEqual
	TokenTypeNotEqual
	TokenTypeNotLessThan
	TokenTypeNotLessThanEqual
	TokenTypeNotGreaterThan
	TokenTypeNotGreaterThanEqual
	TokenTypeSpecialOperator TokenType = iota + 100 // Define a new token type for special operators
)
